### ISSUE TITLE
User Login BugReport

### ISSUE THREAD

**Issue by Joyykim** [jeonyh0924/fc-insta#9]
members.views.UserModelViewAPI - login method
https://github.com/jeonyh0924/fc-insta/blob/master/app/members/views.py#L24

Line 27에서 올바르지 않은 이메일, 비밀번호로 authenticate 함수를 실행할 경우 None을 리턴하는데 그에 대한 예외처리가 필요해 보입니다.
만약 지금의 코드에서 올바르지 않은 이메일, 비밀번호로 로그인 요청을 할 경우 Line 31에서 에러가 발생하지 않을까 싶습니다.
👍

**Comment by jeonyh0924** [comment]
try:
 user = authenticate(request, email, password)
except User.DoesNotExit: 
또는 objectsDoseNotExists 등을 사용하려 하였으나 None에 대한 예외처리를 찾지 못하여  if문을 통한 raise를 발생시켰습니다.
추가적으로 except를 찾게 되면 수정하도록 하겠습니다!
